[profile.default]
src = 'src'
out = 'out'
libs = ['lib', 'lib_fork']
fs_permissions = [
    { access = "read", path = "./out/" },
    { access = "read", path = "./broadcast/" },
]

solc_version = "0.8.21"